environment:
  matrix:
    - nodejs_version: '16'
install:
  - set LIB=C:\OpenSSL-Win64\lib;%LIB%
  - set INCLUDE=C:\OpenSSL-Win64\include;%INCLUDE%
  - set CI=true
  - move "C:\Program Files\Git\usr\bin\msys-2.0.dll" "C:\Program Files\Git\usr\bin\msys-2.0-bak.dll"
  - npm i ololog
  - npm i as-table
  - cmd: build.sh
matrix:
  fast_finish: true
build: off
clone_depth: 1
test_script:
  - refreshenv
cache:
  # - C:\ProgramData\chocolatey\bin
  # - C:\ProgramData\chocolatey\lib
  # - C:\tools\php81
after_build:
  # Remove old or huge cache files to hopefully not exceed the 1GB cache limit.
  #
  # If the cache limit is reached, the cache will not be updated (of not even
  # created in the first run). So this is a trade of between keeping the cache
  # current and having a cache at all.
  # NB: This is done only `on_success` since the cache in uploaded only on
  # success anyway.
  # Show size of cache
